# Setting Keys
KEYCLOAK_URL = "KEYCLOAK_URL"
INTERNAL_KEYCLOAK_URL = "INTERNAL_KEYCLOAK_URL"
REALM = "REALM"
CLIENT_ID = "CLIENT_ID"
CLIENT_SECRET = "CLIENT_SECRET"
USERNAME = "USERNAME"
PASSWORD = "PASSWORD"
EXTENSION_APP_URL = "EXTENSION_APP_URL"
CRM_APP_URL = "CRM_APP_URL"
APISIX_ADMIN_URL = "APISIX_ADMIN_URL"
APISIX_ADMIN_KEY = "APISIX_ADMIN_KEY"
APISIX_GATEWAY_URL = "APISIX_GATEWAY_URL"

# Keycloak Admin API Keys
KC_ADMIN_USER = "KC_ADMIN_USER"
KC_ADMIN_PASSWORD = "KC_ADMIN_PASSWORD"
