# @baseUrl = http://localhost:9080/api/v1
@baseUrl = http://nt2205-ch191-api-alb-455106383.us-east-1.elb.amazonaws.com/api/v1
@keycloakUrl = http://localhost:8080
@realm = zero-trust
@username = testuser
@password = testpassword123
@clientId = test-client
@clientSecret = test-client-secret
@adminUsername = admin
@adminPassword = admin123
@certPath = ../certs/gateway/cert.pem
@keyPath = ../certs/gateway/key.pem
@caPath = ../certs/ca/cert.pem

### 1. Get Access Token
# @name login
POST {{baseUrl}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}
&client_secret={{clientSecret}}
&username={{username}}
&password={{password}}
&grant_type=password

### Variable to store token
@authToken = {{login.response.body.access_token}}

### 2. Call Extension App (which calls CRM App via mTLS)
GET {{baseUrl}}/extension-app/call-crm
Authorization: Bearer {{authToken}}

### 3. Call CRM App Directly (via Gateway)
GET {{baseUrl}}/crm/data
Authorization: Bearer {{authToken}}
