@baseUrl = http://localhost:9080/api/v1
@keycloakUrl = http://localhost:8080
@realm = zero-trust
@username = testuser
@password = testpassword123
@clientId = test-client
@clientSecret = test-client-secret
@adminUsername = admin
@adminPassword = admin123

### 1. Get Access Token
# @name login
POST {{baseUrl}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}
&client_secret={{clientSecret}}
&username={{username}}
&password={{password}}
&grant_type=password

### Variable to store token
@authToken = {{login.response.body.access_token}}

### 2. Call Extension App (which calls CRM App via mTLS)
GET {{baseUrl}}/extension-app/call-crm
Authorization: Bearer {{authToken}}

### 3. Call CRM App Directly (via Gateway)
GET {{baseUrl}}/crm/data
Authorization: Bearer {{authToken}}

### 4. Get Keycloak Admin Token
# @name adminLogin
POST {{keycloakUrl}}/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=admin-cli
&username={{adminUsername}}
&password={{adminPassword}}
&grant_type=password

### Variable to store admin token
@adminToken = {{adminLogin.response.body.access_token}}

### 5. Get All Events
GET {{keycloakUrl}}/admin/realms/{{realm}}/events
Authorization: Bearer {{adminToken}}

### 6. Get LOGIN Events Only
GET {{keycloakUrl}}/admin/realms/{{realm}}/events?type=LOGIN&max=20
Authorization: Bearer {{adminToken}}

### 7. Get LOGIN_ERROR Events
GET {{keycloakUrl}}/admin/realms/{{realm}}/events?type=LOGIN_ERROR&max=20
Authorization: Bearer {{adminToken}}

### 8. Get REFRESH_TOKEN Events
GET {{keycloakUrl}}/admin/realms/{{realm}}/events?type=REFRESH_TOKEN&max=20
Authorization: Bearer {{adminToken}}

### 9. Get INTROSPECT_TOKEN Events
GET {{keycloakUrl}}/admin/realms/{{realm}}/events?type=INTROSPECT_TOKEN&max=20
Authorization: Bearer {{adminToken}}

### 10. Clear All Events
DELETE {{keycloakUrl}}/admin/realms/{{realm}}/events
Authorization: Bearer {{adminToken}}
